"""Remove unnecessary product tables

Revision ID: 0b6bd95bb143
Revises: 
Create Date: 2026-02-11 23:20:08.921183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b6bd95bb143'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productss_id'), table_name='productss')
    op.drop_table('productss')
    op.drop_index(op.f('ix_productsss_id'), table_name='productsss')
    op.drop_table('productsss')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productsss',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('productsss_pkey'))
    )
    op.create_index(op.f('ix_productsss_id'), 'productsss', ['id'], unique=False)
    op.create_table('productss',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('productss_pkey'))
    )
    op.create_index(op.f('ix_productss_id'), 'productss', ['id'], unique=False)
    # ### end Alembic commands ###
