"""Initial Migration

Revision ID: 0cb2c9b853ac
Revises: 
Create Date: 2026-04-07 14:09:16.615431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0cb2c9b853ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Retrieve the 'is_tenant' flag passed from your provision_organization function
    context = op.get_context()
    is_tenant = context.config.attributes.get("is_tenant")
    # print(f"DEBUG: Migration 001 running. is_tenant={is_tenant}")
    
    # If we are in tenant mode, skip creating the 'organization' registry
    if not is_tenant:
        """Upgrade schema."""
        # ONLY run these if we are NOT in a tenant (i.e., we are in public)
        op.create_table('organization',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('schema_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('schema_name'),
        schema='public'
        )
        op.create_index(op.f('ix_public_organization_subdomain'), 'organization', ['subdomain'], unique=True, schema='public')
        # ### end Alembic commands ###
        
    
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_organization_subdomain'), table_name='organization', schema='public')
    op.drop_table('organization', schema='public')
    # ### end Alembic commands ###
