"""Create tables

Revision ID: 6e496a67ea14
Revises: 06cf0148a74a
Create Date: 2026-03-02 16:12:27.504182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6e496a67ea14'
down_revision: Union[str, Sequence[str], None] = '06cf0148a74a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'CUSTOMER', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id', 'org_id')
    )
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('cartitems',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cartitems_org_id'), 'cartitems', ['org_id'], unique=False)
    op.create_index(op.f('ix_cartitems_product_id'), 'cartitems', ['product_id'], unique=False)
    op.create_index(op.f('ix_cartitems_user_id'), 'cartitems', ['user_id'], unique=False)
    op.add_column('products', sa.Column('org_id', sa.Uuid(), nullable=False))
    op.add_column('products', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.create_index(op.f('ix_products_org_id'), 'products', ['org_id'], unique=False)
    op.create_foreign_key(None, 'products', 'organization', ['org_id'], ['id'])
    op.drop_column('products', 'desc')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('desc', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_org_id'), table_name='products')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('products', 'name')
    op.drop_column('products', 'org_id')
    op.drop_index(op.f('ix_cartitems_user_id'), table_name='cartitems')
    op.drop_index(op.f('ix_cartitems_product_id'), table_name='cartitems')
    op.drop_index(op.f('ix_cartitems_org_id'), table_name='cartitems')
    op.drop_table('cartitems')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_org_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('user')
    op.drop_table('organization')
    # ### end Alembic commands ###
